name: Update ReaPack index

on:
  push:
    branches: [ main ]
    paths:
      - 'Scripts/**/*.lua'
      - 'Scripts/**/*.ReaperKeyMap'
      - 'Scripts/**/*.ReaperTheme'
      - '.github/workflows/update-index.yml'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install reapack-index
        run: |
          mkdir -p $HOME/bin
          curl -fLo $HOME/bin/reapack-index https://github.com/cfillion/reapack-index/releases/download/v1.2.4/reapack-index-linux
          chmod +x $HOME/bin/reapack-index
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Update index
        run: |
          reapack-index --commit-columns 1

      - name: Commit updated index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update ReaPack index
          file_pattern: index.xml